fix: JPEG is a readable MIME type
While JPEG is an officially supported file type,
callisto is not capable of rendering documents
with attachments of type image/jpeg. This is because
there is a filter in the reader that errors out early
when an unsupported type is detected -- it is just
not up-to-date with the MIME reader.

```
Error: panicked with: "output item has no appropriate format: item has (\"image/jpeg\",), we want (\n  \"image/svg+xml\",\n  \"image/png\",\n  \"image/gif\",\n  \"text/markdown\",\n  \"text/latex\",\n  \"text/plain\",\n)"
   ┌─ @local/callisto:0.2.4/src/reading/rich-object.typ:71:6
   │  
71 │ ╭       panic("output item has no appropriate format: item has " +
72 │ │         repr(item-formats) + ", we want " + repr(normalize-formats(format)))
   │ ╰────────────────────────────────────────────────────────────────────────────^
```

After updating this, callisto correctly renders
documents with JPEG attachments.